# vim:fileencoding=utf-8:foldmethod=marker
include Oceanic_Material.conf
include fonts.conf

shell_integration enabled

cursor_stop_blinking_after 0

scrollback_fill_enlarged_window yes

mouse_hide_wait 1.0

url_style straight
detect_urls yes

copy_on_select clipboard
map ctrl+shift+c copy_to_clipboard
## 🍎
map cmd+c copy_to_clipboard

map ctrl+shift+v paste_from_clipboard
## 🍎
map cmd+v paste_from_clipboard

paste_actions quote-urls-at-prompt,confirm

# Reset the terminal
map f1 clear_terminal reset active

mouse_map middle release ungrabbed paste_from_selection
mouse_map ctrl+shift+left release grabbed,ungrabbed mouse_handle_click link

